pipeline:
  identifier: Build_Roger_BStack_testng_browserstack_harness_1790602052057
  name: Build testng-browserstack-harness
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Roger-BStack/testng-browserstack-harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: BrowserStack Automate Selenium Tests
                  identifier: browserstack_selenium_tests
                  spec:
                    shell: Sh
                    command: |
                      # Optional: Set up your environment dependencies (Example: Java/Maven)
                      # mvn test-compile

                      # Execute your Selenium test suite
                      # The test scripts should pull credentials from the environment variables below
                      #mvn test -DsuiteXmlFile=testng.xml
                      mvn test -Dconfig.file=config/homepage-signin-popup-test.testng.xml
                    envVariables:
                      BROWSERSTACK_USERNAME: <+secrets.getValue("browserstack_username")>
                      BROWSERSTACK_ACCESS_KEY: <+secrets.getValue("browserstack_access_key")>
                      BROWSERSTACK_BUILD_NAME: <+pipeline.identifier>-<+pipeline.sequenceId>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
